[build]
  publish = "dist/viniciuspdionizio/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
